# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "张三疯的个人博客"
brief-intro: 挖坑小能手的埋坑点滴￣□￣｜｜
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zhanggs1994.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: zhanggs1994
facebook_username: zhanggs1994
github_username:  zhanggs1994
email: HelloRyan@live.com
weibo_username: 不愿意透露姓名的张干盛
zhihu_username: 但愿人长久的西
linkedIn_username: zhanggs1994
dribbble_username: zhanggs1994

description_footer: 张三疯的个人博客！

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: zhanggansheng
disqus_shortname: zhanggansheng
intensedebate_comments: true  #intensedebate评论功能
github_username: zhanggs1994
comment_gitment_repo: zhanggs1994.github.io
comment_gitment_clientId: db8557cd4979b24f61dc
comment_gitment_clientSecret: 7c74126e27ee35ae06f09242388df4b93919065b


# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即# f2f29fcc544e16f43fea51de74e85c78
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 2bad8636dca5b833bcb200a448fad981
google_analytics_id: UA-133194493-1 # google 分析追踪id
google_analytics_host: auto

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6

theme: jekyll-theme-cayman